# Generated by Django 5.0.6 on 2024-07-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='SurveyResponse',
        ),
    ]
