# Generated by Django 5.0.6 on 2024-07-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_formdata_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='weight',
            field=models.CharField(default='4  - 6 hrs', max_length=30),
            preserve_default=False,
        ),
    ]
