from rest_framework import serializers
from .models import SurveyResponse

class SurveyResponseSerializer(serializers.ModelSerializer):
    name = serializers.CharField(max_length=255, required=False, allow_blank=True)
    age = serializers.CharField(max_length=10, required=False, allow_blank=True)
    gender = serializers.CharField(max_length=10, required=False, allow_blank=True)
    weight = serializers.CharField(max_length=20, required=False, allow_blank=True)
    working = serializers.CharField(max_length=10, required=False, allow_blank=True)
    work_shift = serializers.CharField(max_length=30, required=False, allow_blank=True)
    job_nature = serializers.CharField(max_length=30, required=False, allow_blank=True)
    lift_heavy_weights = serializers.CharField(max_length=10, required=False, allow_blank=True)
    use_devices_often = serializers.CharField(max_length=10, required=False, allow_blank=True)
    sitting_hours = serializers.CharField(max_length=30, required=False, allow_blank=True)
    fast_food_frequency = serializers.CharField(max_length=30, required=False, allow_blank=True)
    consume_oily_spicy_food = serializers.CharField(max_length=20, required=False, allow_blank=True)
    dinner_time = serializers.CharField(max_length=30, required=False, allow_blank=True)
    digestion_problems = serializers.CharField(max_length=30, required=False, allow_blank=True)
    stool_frequency = serializers.CharField(max_length=30, required=False, allow_blank=True)
    buttock_pain = serializers.CharField(max_length=20, required=False, allow_blank=True)
    cutting_pain = serializers.CharField(max_length=20, required=False, allow_blank=True)
    burning_sensation = serializers.CharField(max_length=20, required=False, allow_blank=True)
    itching = serializers.CharField(max_length=20, required=False, allow_blank=True)
    pile_mass_coming_out = serializers.CharField(max_length=20, required=False, allow_blank=True)
    pile_mass_condition = serializers.CharField(max_length=30, required=False, allow_blank=True)
    bleeding_issue = serializers.CharField(max_length=20, required=False, allow_blank=True)
    bleeding_type = serializers.CharField(max_length=30, required=False, allow_blank=True)
    bleeding_amount = serializers.CharField(max_length=30, required=False, allow_blank=True)
    blood_color = serializers.CharField(max_length=20, required=False, allow_blank=True)
    pus_discharge = serializers.CharField(max_length=20, required=False, allow_blank=True)
    boils_around_anus = serializers.CharField(max_length=20, required=False, allow_blank=True)
    anus_swelling = serializers.CharField(max_length=20, required=False, allow_blank=True)
    first_time_swelling = serializers.CharField(max_length=20, required=False, allow_blank=True)
    body_hair_type = serializers.CharField(max_length=30, required=False, allow_blank=True)
    diabetes = serializers.CharField(max_length=20, required=False, allow_blank=True)
    redness_swelling = serializers.CharField(max_length=20, required=False, allow_blank=True)
    treatment_type = serializers.CharField(max_length=30, required=False, allow_blank=True)
    treatment_kind = serializers.CharField(max_length=20, required=False, allow_blank=True)
    blood_color_during_treatment = serializers.CharField(max_length=20, required=False, allow_blank=True)
    recurrence = serializers.CharField(max_length=20, required=False, allow_blank=True)
    relapse_frequency = serializers.CharField(max_length=30, required=False, allow_blank=True)
    pain_while_sitting = serializers.CharField(max_length=20, required=False, allow_blank=True)
    pain_while_defecation = serializers.CharField(max_length=20, required=False, allow_blank=True)
    weight_loss = serializers.CharField(max_length=20, required=False, allow_blank=True)
    just_delivered_baby = serializers.CharField(max_length=20, required=False, allow_blank=True)
    family_anal_cancer = serializers.CharField(max_length=20, required=False, allow_blank=True)
    first_time_doctor_visit = serializers.CharField(max_length=20, required=False, allow_blank=True)

    class Meta:
        model = SurveyResponse
        fields = '__all__'
